"""empty message

Revision ID: 2cda850a493b
Revises: 62ad92317fa6
Create Date: 2020-03-02 17:28:10.852661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cda850a493b'
down_revision = '62ad92317fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voters_table', 'poll_name')
    op.drop_column('voters_table', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voters_table', sa.Column('username', mysql.VARCHAR(length=40), nullable=True))
    op.add_column('voters_table', sa.Column('poll_name', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
