"""empty message

Revision ID: 35b09d94f24f
Revises: 
Create Date: 2020-03-06 17:46:01.059074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b09d94f24f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=70), nullable=True),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.Column('poll_question', sa.String(length=100), nullable=True),
    sa.Column('poll_description', sa.String(length=500), nullable=True),
    sa.Column('info_link', sa.String(length=200), nullable=True),
    sa.Column('image_link', sa.String(length=600), nullable=True),
    sa.Column('date_started', sa.DateTime(), nullable=True),
    sa.Column('option1', sa.String(length=150), nullable=False),
    sa.Column('option2', sa.String(length=150), nullable=False),
    sa.Column('option3', sa.String(length=150), nullable=True),
    sa.Column('option4', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voters_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('poll_name', sa.String(length=100), nullable=True),
    sa.Column('option_picked', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voters_table')
    op.drop_table('polls')
    op.drop_table('users')
    # ### end Alembic commands ###
