"""empty message

Revision ID: 4b7e951dc1a6
Revises: 6f3347d5c3c4
Create Date: 2020-03-03 15:14:12.795656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7e951dc1a6'
down_revision = '6f3347d5c3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voters_table', sa.Column('option_picked', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voters_table', 'option_picked')
    # ### end Alembic commands ###
