"""empty message

Revision ID: 62ad92317fa6
Revises: 578f85ee244e
Create Date: 2020-03-02 16:51:02.767106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ad92317fa6'
down_revision = '578f85ee244e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voters_table', sa.Column('poll_name', sa.String(length=100), nullable=True))
    op.add_column('voters_table', sa.Column('username', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voters_table', 'username')
    op.drop_column('voters_table', 'poll_name')
    # ### end Alembic commands ###
