"""empty message

Revision ID: 6f3347d5c3c4
Revises: 2cda850a493b
Create Date: 2020-03-02 17:45:43.213523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3347d5c3c4'
down_revision = '2cda850a493b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voters_table', sa.Column('poll_name', sa.String(length=100), nullable=True))
    op.add_column('voters_table', sa.Column('username', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voters_table', 'username')
    op.drop_column('voters_table', 'poll_name')
    # ### end Alembic commands ###
