"""empty message

Revision ID: 81143ffabf8c
Revises: 4b7e951dc1a6
Create Date: 2020-03-04 19:27:53.470084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81143ffabf8c'
down_revision = '4b7e951dc1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('image_link', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polls', 'image_link')
    # ### end Alembic commands ###
