"""empty message

Revision ID: bcb0bceeb4b1
Revises: 071bae656fa6
Create Date: 2020-03-02 15:57:58.106644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcb0bceeb4b1'
down_revision = '071bae656fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('polls', 'option1',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('polls', 'option2',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('polls', 'option2',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('polls', 'option1',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
