"""empty message

Revision ID: d5a2f39afc12
Revises: 4e1b6576ecab
Create Date: 2020-02-26 15:56:22.491165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5a2f39afc12'
down_revision = '4e1b6576ecab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('polls_ibfk_1', 'polls', type_='foreignkey')
    op.create_foreign_key(None, 'polls', 'users', ['user_id'], ['id'])
    op.drop_column('polls', 'useer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('useer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'polls', type_='foreignkey')
    op.create_foreign_key('polls_ibfk_1', 'polls', 'users', ['useer_id'], ['id'])
    op.drop_column('polls', 'user_id')
    # ### end Alembic commands ###
